DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS box;
DROP TABLE IF EXISTS product;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE box(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    received TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL
);

CREATE TABLE product(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    box_id INTEGER NOT NULL,
    producer_name TEXT NOT NULL,
    product_name TEXT NOT NULL,
    size NUMERIC NOT NULL,
    units TEXT NOT NULL,
    in_stock BOOLEAN NOT NULL DEFAULT TRUE
);
